### ISSUE TITLE
Any chance of removing the following styles

### ISSUE THREAD

**Issue by farzd** [rohitkrai03/pills#2]
Firstly fantastic framework, secondly I see this as an agnostic framework - just for grids which needs to be accompanied with a reset and other formatting styles, so with that said, is it necessary to have these styles as they will be included in the reset?

``` css
html, body {
  margin: 0;
  padding: 0; }

*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box; } 
```

also would be nice for the row to not have a predefined max-width
